remote_theme: BDHU/minimalist
title: Tyler Carberry
logo: https://avatars.githubusercontent.com/u/6628497
sidebar:
  - name: GitHub
    icon: <i class="fa-brands fa-github"></i>
    link: https://github.com/TylerCarberry
  - name: LinkedIn
    icon: <i class="fa-brands fa-linkedin"></i>
    link: https://www.linkedin.com/in/tylercarberry/
